#!/bin/zsh

ln -sf "$PWD/.vim" "$HOME"
ln -sf "$PWD/.tmux.conf" "$HOME"
ln -sf "$PWD/.vimrc" "$HOME"
ln -sf "$PWD/.zshrc" "$HOME"
ln -sf "$PWD/.p10k.zsh" "$HOME"
ln -sf "$PWD/.aliases.zsh" "$HOME"
ln -sf "$PWD/.functions.zsh" "$HOME"
ln -sf "$PWD/.exports.zsh" "$HOME"
